// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp3iZGjBAfKkMwN7tVyQNPN1c1D7tuwHs',
    appId: '1:351259373971:web:193b91b20d1c531d70f866',
    messagingSenderId: '351259373971',
    projectId: 'security-delivery-system',
    authDomain: 'security-delivery-system.firebaseapp.com',
    databaseURL: 'https://security-delivery-system-default-rtdb.firebaseio.com',
    storageBucket: 'security-delivery-system.firebasestorage.app',
    measurementId: 'G-49V5WZFB2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTCV7pJFb_BiPebKQEFTLdg3cUCOZbn40',
    appId: '1:351259373971:android:1726b38f50d10cfb70f866',
    messagingSenderId: '351259373971',
    projectId: 'security-delivery-system',
    databaseURL: 'https://security-delivery-system-default-rtdb.firebaseio.com',
    storageBucket: 'security-delivery-system.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp3iZGjBAfKkMwN7tVyQNPN1c1D7tuwHs',
    appId: '1:351259373971:web:b72a79ae3151cf9970f866',
    messagingSenderId: '351259373971',
    projectId: 'security-delivery-system',
    authDomain: 'security-delivery-system.firebaseapp.com',
    databaseURL: 'https://security-delivery-system-default-rtdb.firebaseio.com',
    storageBucket: 'security-delivery-system.firebasestorage.app',
    measurementId: 'G-S7PBDQPFCC',
  );
}
